# Generated by Django 4.2.6 on 2023-12-08 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_Name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('capital_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('capital_Name', models.CharField(max_length=100)),
                ('country_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
    ]
